name: 'Copy a folder to the remote server'

description: 'This action will copy a folder from runner to the target Windows server'

inputs:
  sourcefile:
    description: 'The source folder to be copied to the remove server'
    required: true
  targetfolder:
    description: 'The target zip file folder on remove server'
    required: true
  filename:
    description: 'The zip file name'
    required: true
  archivefolder:
    description: 'The archive folder name'
    required: true
  keepnfiles:
    description: 'Keep number of backups in the archive folder'
    required: true
  server:
    description: 'The name of the target server'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $password_string = @'
        ${{ inputs.service-account-password }}
        '@
        $secure_password = ConvertTo-SecureString -String $password_string -AsPlainText -Force
        ${{ github.action_path }}/transfer-unzip-archive.ps1 `
          -sourcefolder '${{ inputs.sourcefolder }}' `
          -targetfolder '${{ inputs.targetfolder }}' `
          -filename '${{ inputs.filename }}' `
          -archivefolder '${{ inputs.archivefolder }}' `
          -keepnfiles '${{ inputs.keepnfiles }}' `
          -server '${{ inputs.server }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password