name: 'Compress the local artifacts folder'

description: 'This action will compress the artifacts folder for deployment'

inputs:
  sourcefolder:
    description: 'The source folder to be comparessed'
    required: true
  targetfolder:
    description: 'The target zip file folder on remove server'
    required: true
  zipfilename:
    description: 'The zip file name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        ${{ github.action_path }}/zip-local-folder.ps1 `
          -sourcefolder '${{ inputs.sourcefolder }}' `
          -targetfolder '${{ inputs.targetfolder }}' `
          -zipfilename '${{ inputs.zipfilename }}'